# -------------------------------------------------------------------------------------------------
# -- Project          : Mercury+ XU1 Reference Design
# -- File description : Pin assignment and timing constraints file for Mercury PE1
# -- File name        : MercuryXU1_PE1.xdc
# -- Author           : Diana Ungureanu
# -------------------------------------------------------------------------------------------------
# -- Copyright (c) 2018 by Enclustra GmbH, Switzerland. All rights are reserved.
# -- Unauthorized duplication of this document, in whole or in part, by any means is prohibited
# -- without the prior written permission of Enclustra GmbH, Switzerland.
# --
# -- Although Enclustra GmbH believes that the information included in this publication is correct
# -- as of the date of publication, Enclustra GmbH reserves the right to make changes at any time
# -- without notice.
# --
# -- All information in this document may only be published by Enclustra GmbH, Switzerland.
# -------------------------------------------------------------------------------------------------
# -- Notes:
# -- The IO standards might need to be adapted to your design
# -------------------------------------------------------------------------------------------------
# -- File history:
# --
# -- Version | Date       | Author             | Remarks
# -- ----------------------------------------------------------------------------------------------
# -- 1.0     | 22.12.2016 | D. Ungureanu       | First released version
# -- 2.0     | 20.10.2017 | D. Ungureanu       | Consistency checks
# -- 3.0     | 11.06.2018 | D. Ungureanu       | Consistency checks
# --
# -------------------------------------------------------------------------------------------------

set_property BITSTREAM.CONFIG.OVERTEMPSHUTDOWN ENABLE [current_design]

# ----------------------------------------------------------------------------------
# Important! Do not remove this constraint!
# This property ensures that all unused pins are set to high impedance.
# If the constraint is removed, all unused pins have to be set to HiZ in the top level file.
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]
# ----------------------------------------------------------------------------------

# -------------------------------------------------------------------------------------------------
# LEDs
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN AE8 [get_ports {Led2_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {Led2_N}]

# -------------------------------------------------------------------------------------------------
# I2C on PL side
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN V3 [get_ports {I2c_Scl}]
set_property IOSTANDARD LVCMOS18 [get_ports {I2c_Scl}]

set_property PACKAGE_PIN Y7 [get_ports {I2c_Sda}]
set_property IOSTANDARD LVCMOS18 [get_ports {I2c_Sda}]

# -------------------------------------------------------------------------------------------------
# bank 64
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN AG4   [get_ports {IO_B64_AG4}]
set_property PACKAGE_PIN AG9   [get_ports {IO_B64_AG9}]
set_property PACKAGE_PIN AH11  [get_ports {IO_B64_AH11}]
set_property PACKAGE_PIN AJ1   [get_ports {IO_B64_AJ1}]
set_property PACKAGE_PIN AK8   [get_ports {FPGA_SDATA}]
set_property PACKAGE_PIN AK9   [get_ports {SEL0}]
set_property PACKAGE_PIN AH7   [get_ports {SMA_TRIG}]
set_property PACKAGE_PIN AJ7   [get_ports {IO_B64_L11_GC_AJ7_N}]
set_property PACKAGE_PIN AG8   [get_ports {SEL4}]
set_property PACKAGE_PIN AH8   [get_ports {SEL3}]
set_property PACKAGE_PIN AG5   [get_ports {ADC3_DB1_n}]
set_property PACKAGE_PIN AG6   [get_ports {ADC3_DB1_p}]
set_property PACKAGE_PIN AH6   [get_ports {ADC4_DC1_p}]
set_property PACKAGE_PIN AJ6   [get_ports {ADC4_DC1_n}]
set_property PACKAGE_PIN AK6   [get_ports {ADC3_DA0_n}]
set_property PACKAGE_PIN AK7   [get_ports {ADC3_DA0_p}]
set_property PACKAGE_PIN AF5   [get_ports {ADC4_DD1_n}]
set_property PACKAGE_PIN AF6   [get_ports {ADC4_DD1_p}]
set_property PACKAGE_PIN AJ5   [get_ports {ADC4_DD0_p}]
set_property PACKAGE_PIN AK5   [get_ports {ADC4_DD0_n}]
set_property PACKAGE_PIN AH4   [get_ports {ADC4_DC0_p}]
set_property PACKAGE_PIN AJ4   [get_ports {ADC4_DC0_n}]
set_property PACKAGE_PIN AK3   [get_ports {ADC3_DA1_n}]
set_property PACKAGE_PIN AK4   [get_ports {ADC3_DA1_p}]
set_property PACKAGE_PIN AF11  [get_ports {RJ45_LVDS_TRIG_p}]
set_property PACKAGE_PIN AG11  [get_ports {RJ45_LVDS_TRIG_n}]
set_property PACKAGE_PIN AH2   [get_ports {ADC3_DB0_n}]
set_property PACKAGE_PIN AH3   [get_ports {ADC3_DB0_p}]
set_property PACKAGE_PIN AJ2   [get_ports {ADC4_FCLK_p}]
set_property PACKAGE_PIN AK2   [get_ports {ADC4_FCLK_n}]
set_property PACKAGE_PIN AG1   [get_ports {ADC4_DB1_p}]
set_property PACKAGE_PIN AH1   [get_ports {ADC4_DB1_n}]
set_property PACKAGE_PIN AF3   [get_ports {ADC3_FCLK_p}]
set_property PACKAGE_PIN AG3   [get_ports {ADC3_FCLK_n}]
set_property PACKAGE_PIN AF1   [get_ports {ADC4_DB0_n}]
set_property PACKAGE_PIN AF2   [get_ports {ADC4_DB0_p}]
set_property PACKAGE_PIN AG13  [get_ports {IO_B64_L2_AG13_P}]
set_property PACKAGE_PIN AH13  [get_ports {IO_B64_L2_AH13_N}]
set_property PACKAGE_PIN AH12  [get_ports {UART_SEL_0}]
set_property PACKAGE_PIN AJ12  [get_ports {UART_SEL_1}]
set_property PACKAGE_PIN AK12  [get_ports {SMA_CLK}]
set_property PACKAGE_PIN AK13  [get_ports {UART_SEL_4}]
set_property PACKAGE_PIN AJ11  [get_ports {UART_SEL_2}]
set_property PACKAGE_PIN AK11  [get_ports {UART_SEL_3}]
set_property PACKAGE_PIN AJ10  [get_ports {FPGA_SCLK}]
set_property PACKAGE_PIN AK10  [get_ports {FPGA_SDOUT}]
set_property PACKAGE_PIN AF7   [get_ports {SEL5}]
set_property PACKAGE_PIN AF8   [get_ports {SEL6}]
set_property PACKAGE_PIN AF10  [get_ports {MAX10_SPARE1}]
set_property PACKAGE_PIN AG10  [get_ports {MAX10_SPARE0}]
set_property PACKAGE_PIN AH9   [get_ports {SEL2}]
set_property PACKAGE_PIN AJ9   [get_ports {SEL1}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_B64_AG4}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B64_AG9}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B64_AH11}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B64_AJ1}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_SDATA}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEL0}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMA_TRIG}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B64_L11_GC_AJ7_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEL4}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEL3}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_DB1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_DB1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_DC1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_DC1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_DA0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_DA0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_DD1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_DD1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_DD0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_DD0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_DC0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_DC0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_DA1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_DA1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {RJ45_LVDS_TRIG_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {RJ45_LVDS_TRIG_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_DB0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_DB0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_FCLK_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_FCLK_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_DB1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_DB1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_FCLK_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_FCLK_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_DB0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_DB0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B64_L2_AG13_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B64_L2_AH13_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_SEL_0}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_SEL_1}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMA_CLK}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_SEL_4}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_SEL_2}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_SEL_3}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_SCLK}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_SDOUT}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEL5}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEL6}]
set_property IOSTANDARD LVCMOS18 [get_ports {MAX10_SPARE1}]
set_property IOSTANDARD LVCMOS18 [get_ports {MAX10_SPARE0}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEL2}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEL1}]

# -------------------------------------------------------------------------------------------------
# bank 65
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN AE1   [get_ports {IO_B65_AE1}]
set_property PACKAGE_PIN AE7   [get_ports {IO_B65_AE7}]
set_property PACKAGE_PIN AA7   [get_ports {ADC1_DC1_n}]
set_property PACKAGE_PIN AA8   [get_ports {ADC1_DC1_p}]
set_property PACKAGE_PIN AC7   [get_ports {IO_B65_L11_GC_AC7_P}]
set_property PACKAGE_PIN AD7   [get_ports {IO_B65_L11_GC_AD7_N}]
set_property PACKAGE_PIN AB8   [get_ports {ADC1_DCLK_p}]
set_property PACKAGE_PIN AC8   [get_ports {ADC1_DCLK_n}]
set_property PACKAGE_PIN AB5   [get_ports {ADC0_DC1_n}]
set_property PACKAGE_PIN AB6   [get_ports {ADC0_DC1_p}]
set_property PACKAGE_PIN AC6   [get_ports {ADC0_DB0_p}]
set_property PACKAGE_PIN AD6   [get_ports {ADC0_DB0_n}]
set_property PACKAGE_PIN AA5   [get_ports {ADC0_DD1_n}]
set_property PACKAGE_PIN AA6   [get_ports {ADC0_DD1_p}]
set_property PACKAGE_PIN AD5   [get_ports {ADC1_DA1_p}]
set_property PACKAGE_PIN AE5   [get_ports {ADC1_DA1_n}]
set_property PACKAGE_PIN AD4   [get_ports {ADC1_DB0_p}]
set_property PACKAGE_PIN AE4   [get_ports {ADC1_DB0_n}]
set_property PACKAGE_PIN AB4   [get_ports {ADC1_DA0_p}]
set_property PACKAGE_PIN AC4   [get_ports {ADC1_DA0_n}]
set_property PACKAGE_PIN AB3   [get_ports {ADC0_DB1_p}]
set_property PACKAGE_PIN AC3   [get_ports {ADC0_DB1_n}]
set_property PACKAGE_PIN AB13  [get_ports {ADC3_DC0_p}]
set_property PACKAGE_PIN AC13  [get_ports {ADC3_DC0_n}]
set_property PACKAGE_PIN AE2   [get_ports {ADC0_DD0_n}]
set_property PACKAGE_PIN AE3   [get_ports {ADC0_DD0_p}]
set_property PACKAGE_PIN AC2   [get_ports {ADC0_DC0_p}]
set_property PACKAGE_PIN AD2   [get_ports {ADC0_DC0_n}]
set_property PACKAGE_PIN AC1   [get_ports {ADC0_FCLK_p}]
set_property PACKAGE_PIN AD1   [get_ports {ADC0_FCLK_n}]
set_property PACKAGE_PIN AA2   [get_ports {ADC0_DA0_n}]
set_property PACKAGE_PIN AA3   [get_ports {ADC0_DA0_p}]
set_property PACKAGE_PIN AB1   [get_ports {IO_B65_L24_PERST_AB1_N_n}]
set_property PACKAGE_PIN AA1   [get_ports {ADC0_DA1_p}]
set_property PACKAGE_PIN AE13  [get_ports {ADC3_DC1_p}]
set_property PACKAGE_PIN AF13  [get_ports {ADC3_DC1_n}]
set_property PACKAGE_PIN AD12  [get_ports {IO_B65_L3_AD15_AD12_P}]
set_property PACKAGE_PIN AE12  [get_ports {IO_B65_L3_AD15_AE12_N}]
set_property PACKAGE_PIN AC11  [get_ports {IO_B65_L4_AD7_AC11_P}]
set_property PACKAGE_PIN AD11  [get_ports {IO_B65_L4_AD7_AD11_N}]
set_property PACKAGE_PIN AA11  [get_ports {IO_B65_L5_AD14_AA11_N}]
set_property PACKAGE_PIN AA12  [get_ports {IO_B65_L5_AD14_AA12_P}]
set_property PACKAGE_PIN AB10  [get_ports {ADC1_DD0_n}]
set_property PACKAGE_PIN AB11  [get_ports {ADC1_DD0_p}]
set_property PACKAGE_PIN AB9   [get_ports {ADC1_DC0_p}]
set_property PACKAGE_PIN AC9   [get_ports {ADC1_DC0_n}]
set_property PACKAGE_PIN AD10  [get_ports {ADC1_DB1_p}]
set_property PACKAGE_PIN AE10  [get_ports {ADC1_DB1_n}]
set_property PACKAGE_PIN AD9   [get_ports {ADC1_FCLK_p}]
set_property PACKAGE_PIN AE9   [get_ports {ADC1_FCLK_n}]

set_property IOSTANDARD LVCMOS18 [get_ports {IO_B65_AE1}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B65_AE7}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DC1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DC1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B65_L11_GC_AC7_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B65_L11_GC_AD7_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DCLK_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DCLK_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DC1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DC1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DB0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DB0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DD1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DD1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DA1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DA1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DB0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DB0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DA0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DA0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DB1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DB1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_DC0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_DC0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DD0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DD0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DC0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DC0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_FCLK_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_FCLK_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DA0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DA0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B65_L24_PERST_AB1_N_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_DA1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_DC1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_DC1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B65_L3_AD15_AD12_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B65_L3_AD15_AE12_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B65_L4_AD7_AC11_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B65_L4_AD7_AD11_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B65_L5_AD14_AA11_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B65_L5_AD14_AA12_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DD0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DD0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DC0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DC0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DB1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DB1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_FCLK_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_FCLK_n}]

# -------------------------------------------------------------------------------------------------
# bank 66
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN U6   [get_ports {ADC1_SEN}]
set_property PACKAGE_PIN U7   [get_ports {ADC0_SEN}]
set_property PACKAGE_PIN V6   [get_ports {IO_B66_L11_GC_V6_N}]
set_property PACKAGE_PIN V7   [get_ports {IO_B66_L11_GC_V7_P}]
set_property PACKAGE_PIN W6   [get_ports {ADC1_DD1_n}]
set_property PACKAGE_PIN W7   [get_ports {ADC1_DD1_p}]
set_property PACKAGE_PIN U8   [get_ports {IO_B66_L13_GC_U8_P}]
set_property PACKAGE_PIN V8   [get_ports {IO_B66_L13_GC_V8_N}]
set_property PACKAGE_PIN Y8   [get_ports {IO_B66_L14_GC_Y8_N}]
set_property PACKAGE_PIN Y9   [get_ports {IO_B66_L14_GC_Y9_P}]
set_property PACKAGE_PIN U11  [get_ports {IO_B66_L15_AD11_U11_P}]
set_property PACKAGE_PIN V11  [get_ports {IO_B66_L15_AD11_V11_N}]
set_property PACKAGE_PIN W10  [get_ports {IO_B66_L16_AD3_W10_N}]
set_property PACKAGE_PIN W11  [get_ports {IO_B66_L16_AD3_W11_P}]
set_property PACKAGE_PIN U9   [get_ports {IO_B66_L17_AD10_U9_P}]
set_property PACKAGE_PIN V9   [get_ports {IO_B66_L17_AD10_V9_N}]
set_property PACKAGE_PIN T11  [get_ports {IO_B66_L18_AD2_T11_P}]
set_property PACKAGE_PIN U10  [get_ports {IO_B66_L18_AD2_U10_N}]
set_property PACKAGE_PIN T10  [get_ports {IO_B66_L19_AD9_T10_N}]
set_property PACKAGE_PIN R10  [get_ports {IO_B66_L19_AD9_R10_P}]
set_property PACKAGE_PIN Y3   [get_ports {MAX10_SPARE2}]
set_property PACKAGE_PIN Y4   [get_ports {MAX10_SPARE4}]
set_property PACKAGE_PIN P10  [get_ports {IO_B66_L20_AD1_P10_N}]
set_property PACKAGE_PIN P11  [get_ports {IO_B66_L20_AD1_P11_P}]
set_property PACKAGE_PIN M12  [get_ports {IO_B66_L21_AD8_M12_N}]
set_property PACKAGE_PIN N12  [get_ports {IO_B66_L21_AD8_N12_P}]
set_property PACKAGE_PIN M10  [get_ports {IO_B66_L22_AD0_M10_N}]
set_property PACKAGE_PIN N10  [get_ports {IO_B66_L22_AD0_N10_P}]
set_property PACKAGE_PIN L11  [get_ports {IO_B66_L23_L11_N}]
set_property PACKAGE_PIN L12  [get_ports {IO_B66_L23_L12_P}]
set_property PACKAGE_PIN K10  [get_ports {IO_B66_L24_K10_N}]
set_property PACKAGE_PIN L10  [get_ports {IO_B66_L24_L10_P}]
set_property PACKAGE_PIN Y1   [get_ports {MAX10_SPARE3}]
set_property PACKAGE_PIN Y2   [get_ports {MAX10_SPARE5}]
set_property PACKAGE_PIN W1   [get_ports {IO_B66_L3_AD15_W1_N}]
set_property PACKAGE_PIN W2   [get_ports {IO_B66_L3_AD15_W2_P}]
set_property PACKAGE_PIN V1   [get_ports {IO_B66_L4_AD7_V1_N}]
set_property PACKAGE_PIN V2   [get_ports {IO_B66_L4_AD7_V2_P}]
set_property PACKAGE_PIN U2   [get_ports {IO_B66_L5_AD14_U2_P}]
set_property PACKAGE_PIN U3   [get_ports {IO_B66_L5_AD14_U3_N}]
set_property PACKAGE_PIN T1   [get_ports {ADC3_SEN}]
set_property PACKAGE_PIN U1   [get_ports {ADC4_SEN}]
set_property PACKAGE_PIN W5   [get_ports {ADC_PDN}]
set_property PACKAGE_PIN Y5   [get_ports {ADC_RST}]
set_property PACKAGE_PIN V4   [get_ports {ADC_SDOUT}]
set_property PACKAGE_PIN W4   [get_ports {ADC2_SEN}]
set_property PACKAGE_PIN U4   [get_ports {ADC_SDATA}]
set_property PACKAGE_PIN U5   [get_ports {ADC_SCLK}]
set_property PACKAGE_PIN N11  [get_ports {IO_B66_N11}]
set_property PACKAGE_PIN Y10  [get_ports {IO_B66_Y10}]

set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_SEN}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC0_SEN}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L11_GC_V6_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L11_GC_V7_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DD1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC1_DD1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L13_GC_U8_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L13_GC_V8_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L14_GC_Y8_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L14_GC_Y9_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L15_AD11_U11_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L15_AD11_V11_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L16_AD3_W10_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L16_AD3_W11_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L17_AD10_U9_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L17_AD10_V9_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L18_AD2_T11_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L18_AD2_U10_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L19_AD9_T10_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L19_AD9_R10_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {MAX10_SPARE2}]
set_property IOSTANDARD LVCMOS18 [get_ports {MAX10_SPARE4}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L20_AD1_P10_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L20_AD1_P11_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L21_AD8_M12_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L21_AD8_N12_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L22_AD0_M10_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L22_AD0_N10_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L23_L11_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L23_L12_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L24_K10_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L24_L10_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {MAX10_SPARE3}]
set_property IOSTANDARD LVCMOS18 [get_ports {MAX10_SPARE5}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L3_AD15_W1_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L3_AD15_W2_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L4_AD7_V1_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L4_AD7_V2_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L5_AD14_U2_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_L5_AD14_U3_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC3_SEN}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC4_SEN}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC_PDN}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC_RST}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC_SDOUT}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_SEN}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC_SDATA}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC_SCLK}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_N11}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B66_Y10}]


# -------------------------------------------------------------------------------------------------
# bank 48
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN G11  [get_ports {ADC2_DD1_n}]
set_property PACKAGE_PIN H12  [get_ports {ADC2_DD1_p}]
set_property PACKAGE_PIN H11  [get_ports {ADC2_DD0_n}]
set_property PACKAGE_PIN J12  [get_ports {ADC2_DD0_p}]
set_property PACKAGE_PIN J10  [get_ports {ADC2_DC1_n}]
set_property PACKAGE_PIN J11  [get_ports {ADC2_DC1_p}]
set_property PACKAGE_PIN B11  [get_ports {IO_B48_L1_AD15_B11_N}]
set_property PACKAGE_PIN C12  [get_ports {IO_B48_L1_AD15_C12_P}]
set_property PACKAGE_PIN A11  [get_ports {IO_B48_L2_AD14_A11_N}]
set_property PACKAGE_PIN A12  [get_ports {IO_B48_L2_AD14_A12_P}]
set_property PACKAGE_PIN A10  [get_ports {IO_B48_L3_AD13_A10_N}]
set_property PACKAGE_PIN B10  [get_ports {IO_B48_L3_AD13_B10_P}]
set_property PACKAGE_PIN C11  [get_ports {IO_B48_L4_AD12_C11_N}]
set_property PACKAGE_PIN D11  [get_ports {IO_B48_L4_AD12_D11_P}]
set_property PACKAGE_PIN D12  [get_ports {IO_B48_L5_HDGC_D12_N}]
set_property PACKAGE_PIN E12  [get_ports {IO_B48_L5_HDGC_E12_P}]
set_property PACKAGE_PIN D10  [get_ports {IO_B48_L6_HDGC_D10_N}]
set_property PACKAGE_PIN E10  [get_ports {IO_B48_L6_HDGC_E10_P}]
set_property PACKAGE_PIN F11  [get_ports {ADC2_FCLK_n}]
set_property PACKAGE_PIN F12  [get_ports {ADC2_FCLK_p}]
set_property PACKAGE_PIN F10  [get_ports {PEO_LVDS_TRIG_n}]
set_property PACKAGE_PIN G10  [get_ports {PEO_LVDS_TRIG_p}]
set_property PACKAGE_PIN K12  [get_ports {ADC2_DC0_n}]
set_property PACKAGE_PIN K13  [get_ports {ADC2_DC0_p}]

set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DD1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DD1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DD0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DD0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DC1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DC1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L1_AD15_B11_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L1_AD15_C12_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L2_AD14_A11_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L2_AD14_A12_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L3_AD13_A10_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L3_AD13_B10_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L4_AD12_C11_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L4_AD12_D11_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L5_HDGC_D12_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L5_HDGC_E12_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L6_HDGC_D10_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L6_HDGC_E10_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_FCLK_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_FCLK_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {PEO_LVDS_TRIG_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {PEO_LVDS_TRIG_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DC0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DC0_p}]

# -------------------------------------------------------------------------------------------------
# bank 47
# -------------------------------------------------------------------------------------------------

set_property PACKAGE_PIN J15  [get_ports {ADC2_DB0_n}]
set_property PACKAGE_PIN K15  [get_ports {ADC2_DB0_p}]
set_property PACKAGE_PIN J14  [get_ports {LVDS_SMA_RJ45_CLK1_N}]
set_property PACKAGE_PIN K14  [get_ports {LVDS_SMA_RJ45_CLK1_P}]
set_property PACKAGE_PIN H13  [get_ports {IO_B47_L12_AD0_H13_N}]
set_property PACKAGE_PIN H14  [get_ports {IO_B47_L12_AD0_H14_P}]
set_property PACKAGE_PIN A15  [get_ports {IO_B47_L1_AD11_A15_N}]
set_property PACKAGE_PIN B15  [get_ports {IO_B47_L1_AD11_B15_P}]
set_property PACKAGE_PIN A14  [get_ports {IO_B47_L2_AD10_A14_N}]
set_property PACKAGE_PIN B14  [get_ports {IO_B47_L2_AD10_B14_P}]
set_property PACKAGE_PIN A13  [get_ports {IO_B47_L3_AD9_A13_N}]
set_property PACKAGE_PIN B13  [get_ports {IO_B47_L3_AD9_B13_P}]
set_property PACKAGE_PIN C13  [get_ports {IO_B47_L4_AD8_C13_N}]
set_property PACKAGE_PIN C14  [get_ports {IO_B47_L4_AD8_C14_P}]
set_property PACKAGE_PIN D14  [get_ports {ADC2_DCLK_n}]
set_property PACKAGE_PIN D15  [get_ports {ADC2_DCLK_p}]
set_property PACKAGE_PIN E13  [get_ports {IO_B47_L6_HDGC_AD6_E13_N}]
set_property PACKAGE_PIN E14  [get_ports {IO_B47_L6_HDGC_AD6_E14_P}]
set_property PACKAGE_PIN E15  [get_ports {ADC2_DA0_n}]
set_property PACKAGE_PIN F15  [get_ports {ADC2_DA0_p}]
set_property PACKAGE_PIN F13  [get_ports {ADC2_DB1_n}]
set_property PACKAGE_PIN G13  [get_ports {ADC2_DB1_p}]
set_property PACKAGE_PIN G14  [get_ports {ADC2_DA1_n}]
set_property PACKAGE_PIN G15  [get_ports {ADC2_DA1_p}]

set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DB0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DB0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {LVDS_SMA_RJ45_CLK1_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {LVDS_SMA_RJ45_CLK1_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B47_L12_AD0_H13_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B47_L12_AD0_H14_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B47_L1_AD11_A15_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B47_L1_AD11_B15_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B47_L2_AD10_A14_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B47_L2_AD10_B14_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B47_L3_AD9_A13_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B47_L3_AD9_B13_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B47_L4_AD8_C13_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B47_L4_AD8_C14_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DCLK_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DCLK_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B47_L6_HDGC_AD6_E13_N}]
set_property IOSTANDARD LVCMOS18 [get_ports {IO_B47_L6_HDGC_AD6_E14_P}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DA0_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DA0_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DB1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DB1_p}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DA1_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {ADC2_DA1_p}]

## #LVDS example
##set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L5_HDGC_D12_N}]
##set_property IOSTANDARD LVCMOS18 [get_ports {IO_B48_L5_HDGC_E12_P}]
##set_property PACKAGE_PIN D11  [get_ports {IO_B48_L4_AD12_D11_P}]

# -------------------------------------------------------------------------------------------------
# PS banks defined in the block design
# -------------------------------------------------------------------------------------------------
