webtalk_init -webtalk_dir C:\\triumf\\nuprism\\proj2\\xu1-nuprism\\XU1-NuPRISM\\SDK_NuPRISM\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-05-05 10:11:37" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211459883_1777531418_210718584_303" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ujlq9sidl90vtqg84tck54e2c6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.041 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1588696272001" -context "sdk\\\\application/1588696272001"
webtalk_add_data -client sdk -key hwid -value "1585068647479" -context "sdk\\\\application/1588696272001"
webtalk_add_data -client sdk -key bspid -value "1585068678355" -context "sdk\\\\application/1588696272001"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1588696272001"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1588696272001"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1588696272001"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1588696272001"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1588696272001"
webtalk_add_data -client sdk -key Procused -value "psu_cortexa53" -context "sdk\\\\application/1588696272001"
webtalk_add_data -client sdk -key projSize -value "242.484375" -context "sdk\\\\application/1588696272001"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1588698697571"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1588698697571"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1588698697571"
webtalk_add_data -client sdk -key DebugCount -value "6" -context "sdk\\\\bsp/1588698697571"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1588698697571"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1588698697571"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1588698697571"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1588698697571"
webtalk_transmit -clientid 1841472510 -regid "211459883_1777531418_210718584_303" -xml C:\\triumf\\nuprism\\proj2\\xu1-nuprism\\XU1-NuPRISM\\SDK_NuPRISM\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\triumf\\nuprism\\proj2\\xu1-nuprism\\XU1-NuPRISM\\SDK_NuPRISM\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\triumf\\nuprism\\proj2\\xu1-nuprism\\XU1-NuPRISM\\SDK_NuPRISM\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
